name: careconnect
description: CareConnect - Blockchain-Powered Aid Platform for Cancer Warrior Foundation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Blockchain (Web3)
  web3dart: ^2.7.1
  http: ^1.1.2
  web_socket_channel: ^2.4.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.0.0
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # QR Code
  qr_flutter: ^4.1.0
  # Removed qr_code_scanner due to Android AGP namespace incompatibility
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # Charts
  fl_chart: ^0.66.0
  
  # Wallet Connect
  walletconnect_dart: 0.0.6
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Crypto
  bip39: ^1.0.6
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - .env
